// <auto-generated />
using System;
using EmpregaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EmpregaAI.Migrations
{
    [DbContext(typeof(AplicacaoContext))]
    [Migration("20260202164818_MigracaoRetiradaDataNascimento")]
    partial class MigracaoRetiradaDataNascimento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmpregaAI.Models.Certificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CargaHoraria")
                        .HasColumnType("integer");

                    b.Property<Guid>("CurriculoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("Excluido")
                        .HasColumnType("boolean");

                    b.Property<string>("Instituicao")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("UrlCertificado")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurriculoId");

                    b.ToTable("Certificacoes");
                });

            modelBuilder.Entity("EmpregaAI.Models.Experiencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cargo")
                        .HasColumnType("text");

                    b.Property<Guid>("CurriculoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<bool>("EmpregoAtual")
                        .HasColumnType("boolean");

                    b.Property<string>("Empresa")
                        .HasColumnType("text");

                    b.Property<bool?>("Excluido")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CurriculoId");

                    b.ToTable("Experiencias");
                });

            modelBuilder.Entity("EmpregaAI.Models.Formacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CurriculoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Curso")
                        .HasColumnType("text");

                    b.Property<bool?>("Excluido")
                        .HasColumnType("boolean");

                    b.Property<string>("Instituicao")
                        .HasColumnType("text");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CurriculoId");

                    b.ToTable("Formacoes");
                });

            modelBuilder.Entity("EmpregaAPI.Models.Curriculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cidade")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<bool?>("Excluido")
                        .HasColumnType("boolean");

                    b.Property<string>("NomeCompleto")
                        .HasColumnType("text");

                    b.Property<string>("Objetivo")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Curriculos");
                });

            modelBuilder.Entity("EmpregaAPI.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Excluido")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EmpregaAI.Models.Certificacao", b =>
                {
                    b.HasOne("EmpregaAPI.Models.Curriculo", "Curriculo")
                        .WithMany("Certificacoes")
                        .HasForeignKey("CurriculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curriculo");
                });

            modelBuilder.Entity("EmpregaAI.Models.Experiencia", b =>
                {
                    b.HasOne("EmpregaAPI.Models.Curriculo", "Curriculo")
                        .WithMany("Experiencias")
                        .HasForeignKey("CurriculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curriculo");
                });

            modelBuilder.Entity("EmpregaAI.Models.Formacao", b =>
                {
                    b.HasOne("EmpregaAPI.Models.Curriculo", "Curriculo")
                        .WithMany("Formacoes")
                        .HasForeignKey("CurriculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curriculo");
                });

            modelBuilder.Entity("EmpregaAPI.Models.Curriculo", b =>
                {
                    b.HasOne("EmpregaAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EmpregaAPI.Models.Curriculo", b =>
                {
                    b.Navigation("Certificacoes");

                    b.Navigation("Experiencias");

                    b.Navigation("Formacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
